package models

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// User represents a row in the users table.
type User struct {
	ID             string     `json:"id"`
	Username       string     `json:"username"`
	Email          string     `json:"email"`
	APIKey         string     `json:"apiKey"`
	Country        *string    `json:"country"`
	Bio            *string    `json:"bio"`
	Website        *string    `json:"website"`
	AvatarURL      *string    `json:"avatarUrl"`
	AvatarPublicID *string    `json:"-"`
	CreatedAt      time.Time  `json:"createdAt"`
	DeletedAt      *time.Time `json:"-"`
}

// FindUserByEmail looks up a user by their email address.
// Returns nil (no error) if no user was found — this is
// normal, not a failure, since a new email means we should
// create a new account instead. (We use magic links ma dude)
func FindUserByEmail(ctx context.Context, pool *pgxpool.Pool, email string) (*User, error) {
	var u User

	err := pool.QueryRow(ctx, `
		SELECT id, username, email, api_key, country, bio, website,
		       avatar_url, avatar_public_id, created_at, deleted_at
		FROM users
		WHERE email = $1 AND deleted_at IS NULL
	`, email).Scan(
		&u.ID, &u.Username, &u.Email, &u.APIKey, &u.Country, &u.Bio,
		&u.Website, &u.AvatarURL, &u.AvatarPublicID, &u.CreatedAt, &u.DeletedAt,
	)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil // no user found, not an error
	}

	if err != nil {
		return nil, err
	}

	return &u, nil
}

// FindUserByUsername looks up a user by username, used to
// check availability during signup.
func FindUserByUsername(ctx context.Context, pool *pgxpool.Pool, username string) (*User, error) {
	var u User

	err := pool.QueryRow(ctx, `
		SELECT id, username, email, api_key, country, bio, website,
		       avatar_url, avatar_public_id, created_at, deleted_at
		FROM users
		WHERE username = $1 AND deleted_at IS NULL
	`, username).Scan(
		&u.ID, &u.Username, &u.Email, &u.APIKey, &u.Country, &u.Bio,
		&u.Website, &u.AvatarURL, &u.AvatarPublicID, &u.CreatedAt, &u.DeletedAt,
	)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	return &u, nil
}

// FindUserByID looks up a user by their ID.
func FindUserByID(ctx context.Context, pool *pgxpool.Pool, id string) (*User, error) {
	var u User

	err := pool.QueryRow(ctx, `
		SELECT id, username, email, api_key, country, bio, website,
		       avatar_url, avatar_public_id, created_at, deleted_at
		FROM users
		WHERE id = $1 AND deleted_at IS NULL
	`, id).Scan(
		&u.ID, &u.Username, &u.Email, &u.APIKey, &u.Country, &u.Bio,
		&u.Website, &u.AvatarURL, &u.AvatarPublicID, &u.CreatedAt, &u.DeletedAt,
	)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	return &u, nil
}

// FindUserByAPIKey looks up a user by their API key, used
// to authenticate editor plugin requests.
func FindUserByAPIKey(ctx context.Context, pool *pgxpool.Pool, apiKey string) (*User, error) {
	var u User

	err := pool.QueryRow(ctx, `
		SELECT id, username, email, api_key, country, bio, website,
		       avatar_url, avatar_public_id, created_at, deleted_at
		FROM users
		WHERE api_key = $1 AND deleted_at IS NULL
	`, apiKey).Scan(
		&u.ID, &u.Username, &u.Email, &u.APIKey, &u.Country, &u.Bio,
		&u.Website, &u.AvatarURL, &u.AvatarPublicID, &u.CreatedAt, &u.DeletedAt,
	)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	return &u, nil
}

// CreateUser inserts a new user with a chosen username and
// display name. api_key and id are generated by the database.
func CreateUser(ctx context.Context, pool *pgxpool.Pool, email, username, displayName string) (*User, error) {
	var u User

	err := pool.QueryRow(ctx, `
		INSERT INTO users (email, username, display_name)
		VALUES ($1, $2, $3)
		RETURNING id, username, email, api_key, country, bio, website,
		          avatar_url, avatar_public_id, created_at, deleted_at
	`, email, username, displayName).Scan(
		&u.ID, &u.Username, &u.Email, &u.APIKey, &u.Country, &u.Bio,
		&u.Website, &u.AvatarURL, &u.AvatarPublicID, &u.CreatedAt, &u.DeletedAt,
	)

	if err != nil {
		return nil, err
	}

	return &u, nil
}

// RegenerateAPIKey generates a new random API key for the
// user, invalidating the old one immediately.
func RegenerateAPIKey(ctx context.Context, pool *pgxpool.Pool, userID string) (string, error) {
	var newKey string

	err := pool.QueryRow(ctx, `
		UPDATE users SET api_key = gen_random_uuid()
		WHERE id = $1
		RETURNING api_key
	`, userID).Scan(&newKey)

	if err != nil {
		return "", err
	}

	return newKey, nil
}
